data:
  root: "/work/nvme/bfdu/dsingh10/data_night/Dataset"
  images:
    train: "/work/nvme/bfdu/dsingh10/data_night/Dataset/train"
    val:   "/work/nvme/bfdu/dsingh10/data_night/Dataset/val"
    test:  "/work/nvme/bfdu/dsingh10/data_night/Dataset/test"
  annotations:
    train: "/work/nvme/bfdu/dsingh10/code/cs444-final/Data_Night/det_train_10k.json"
    val:   "/work/nvme/bfdu/dsingh10/code/cs444-final/Data_Night/det_val_10k.json"
    test:  "/work/nvme/bfdu/dsingh10/code/cs444-final/Data_Night/det_test_10k.json"


model:
  swin_variant: "swin_tiny_patch4_window7_224"
  pretrained: true
  out_channels: 768 
  rpn_anchor_sizes: [[32, 64, 128, 256, 512]]

training:
  epochs: 5
  batch_size: 4
  lr: 0.0001
  weight_decay: 0.0001
  num_workers: 16
  device: "cuda"
  checkpoint_dir: "/work/nvme/bfdu/dsingh10/checkpoints/swin_rcnn"
  log_dir:  "/work/nvme/bfdu/dsingh10/logs/swin_rcnn"
  checkpoint_freq: 1


seed: 42