data:
  root: "/work/nvme/bfdu/ktrikha/data/Dataset"
  images:
    train: "/work/nvme/bfdu/ktrikha/data/Dataset/train"
    val:   "/work/nvme/bfdu/ktrikha/data/Dataset/val"
    test:  "/work/nvme/bfdu/ktrikha/data/Dataset/test"
  annotations:
    train: "/work/nvme/bfdu/ktrikha/code/cs444-final/Data/det_train_10k.json"
    val:   "/work/nvme/bfdu/ktrikha/code/cs444-final/Data/det_val_10k.json"
    test:  "/work/nvme/bfdu/ktrikha/code/cs444-final/Data/det_test_10k.json"


model:
  num_classes: 10
  embed_dim: 128
  num_heads: [4, 8, 16, 32]
  num_blocks: [2, 2, 6, 2]
  window_size: 7
  neck_dim: 256
  decoder_queries: 100

training:
  epochs: 100
  batch_size: 4
  lr: 0.0001
  weight_decay: 0.0001
  num_workers: 16
  device: "cuda"
  checkpoint_dir: "/work/nvme/bfdu/ktrikha/checkpoints/swindetr_LONG"
  log_dir:  "/work/nvme/bfdu/ktrikha/logs/swindetr_LONG"
  checkpoint_freq: 10

seed: 42
