data:
  root: "/work/nvme/bfdu/ktrikha/data/Dataset"
  images:
    train: "/work/nvme/bfdu/ktrikha/data/Dataset/train"
    val:   "/work/nvme/bfdu/ktrikha/data/Dataset/val"
    test:  "/work/nvme/bfdu/ktrikha/data/Dataset/test"
  annotations:
    train: "/work/nvme/bfdu/ktrikha/code/cs444-final/Data/det_train_10k.json"
    val:   "/work/nvme/bfdu/ktrikha/code/cs444-final/Data/det_val_10k.json"
    test:  "/work/nvme/bfdu/ktrikha/code/cs444-final/Data/det_test_10k.json"


model:
  swin_variant: "swin_tiny_patch4_window7_224"
  pretrained: true
  out_channels: 768 
  rpn_anchor_sizes: [[32, 64, 128, 256, 512]]

training:
  epochs: 50
  batch_size: 2
  lr: 0.0001
  weight_decay: 0.0001
  num_workers: 4
  device: "cuda"
  checkpoint_dir: "/work/nvme/bfdu/ktrikha/checkpoints/swin_run1"
  log_dir:  "/work/nvme/bfdu/ktrikha/logs/swin_run1"
  checkpoint_freq: 10


seed: 42